[build]
builder = "nixpacks"
watchPatterns = ["backend/**"]

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
ENVIRONMENT = "production"