# Railway Configuration
[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
startCommand = "python production_main.py"

# Environment variables
[deploy.healthcheckPath]
path = "/health"

[deploy.healthcheckTimeout]
timeout = 300