#!/usr/bin/env python3
"""
Download team logos from ESPN's public site API into frontend/public/team-logos/.

Usage (from repo root):
  cd backend && PYTHONPATH=. python3 scripts/download_espn_team_logos.py
"""

from __future__ import annotations

import json
import re
import time
import urllib.error
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_ROOT = REPO_ROOT / "frontend" / "public" / "team-logos"
REGISTRY_PATH = REPO_ROOT / "frontend" / "src" / "lib" / "team-logo-registry.generated.ts"

# YetAI folder key -> ESPN (sport, league, query)
LEAGUES: dict[str, tuple[str, str, str]] = {
    "nba": ("basketball", "nba", ""),
    "wnba": ("basketball", "wnba", ""),
    "nhl": ("hockey", "nhl", ""),
    "epl": ("soccer", "eng.1", ""),
    "mls": ("soccer", "usa.1", ""),
    "ucl": ("soccer", "uefa.champions", ""),
    "ncaaf": ("football", "college-football", "?limit=500"),
    "ncaab": ("basketball", "mens-college-basketball", "?limit=400"),
}

USER_AGENT = "YetAI-logo-sync/1.0 (+https://github.com/benyetra/YetAI)"


def name_slug(display_name: str) -> str:
    s = display_name.strip().lower()
    s = s.replace("&", " and ")
    s = re.sub(r"[.'']", "", s)
    s = re.sub(r"[^a-z0-9]+", "_", s)
    return s.strip("_")


def fetch_json(url: str) -> dict:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.load(resp)


def download_file(url: str, dest: Path) -> bool:
    dest.parent.mkdir(parents=True, exist_ok=True)
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = resp.read()
        if len(data) < 200:
            return False
        dest.write_bytes(data)
        return True
    except urllib.error.HTTPError:
        return False


def load_teams(sport: str, league: str, query: str) -> list[dict]:
    url = (
        f"https://site.api.espn.com/apis/site/v2/sports/{sport}/{league}/teams"
        f"{query}"
    )
    data = fetch_json(url)
    return data["sports"][0]["leagues"][0]["teams"]


def sync_league(folder: str, sport: str, league: str, query: str) -> dict:
    out_dir = OUT_ROOT / folder
    out_dir.mkdir(parents=True, exist_ok=True)
    teams = load_teams(sport, league, query)

    by_name: dict[str, str] = {}
    by_abbr: dict[str, str] = {}
    abbr_counts: dict[str, int] = {}

    downloaded = 0
    for entry in teams:
        team = entry.get("team") or {}
        display = (team.get("displayName") or team.get("name") or "").strip()
        abbr = (team.get("abbreviation") or "").strip().upper()
        team_id = str(team.get("id") or "").strip()
        logos = team.get("logos") or []
        logo_url = logos[0]["href"] if logos else None
        if not display or not logo_url:
            continue

        stem = name_slug(display)
        if not stem:
            continue

        dest = out_dir / f"{stem}.png"
        if download_file(logo_url, dest):
            downloaded += 1
        else:
            continue

        by_name[stem] = stem

        if abbr:
            abbr_counts[abbr] = abbr_counts.get(abbr, 0) + 1

        time.sleep(0.05)

    # Second pass: abbreviation aliases when unique in league
    for entry in teams:
        team = entry.get("team") or {}
        display = (team.get("displayName") or team.get("name") or "").strip()
        abbr = (team.get("abbreviation") or "").strip().upper()
        if not display or not abbr or abbr_counts.get(abbr, 0) != 1:
            continue
        stem = name_slug(display)
        if stem and stem in by_name:
            by_abbr[abbr] = stem
            abbr_dest = out_dir / f"{abbr.lower()}.png"
            src = out_dir / f"{stem}.png"
            if src.exists() and not abbr_dest.exists():
                abbr_dest.write_bytes(src.read_bytes())

    print(f"  {folder}: {downloaded}/{len(teams)} logos -> {out_dir}")
    return {"byName": by_name, "byAbbr": by_abbr}


def emit_registry(registry: dict) -> None:
    lines = [
        "/** Auto-generated by backend/scripts/download_espn_team_logos.py — do not edit. */",
        "",
        "export type EspnLogoLeague =",
        "  | 'nba'",
        "  | 'wnba'",
        "  | 'nhl'",
        "  | 'epl'",
        "  | 'mls'",
        "  | 'ucl'",
        "  | 'ncaaf'",
        "  | 'ncaab';",
        "",
        "export type TeamLogoRegistryEntry = {",
        "  byName: Record<string, string>;",
        "  byAbbr: Record<string, string>;",
        "};",
        "",
        "export const ESPN_TEAM_LOGO_REGISTRY: Record<EspnLogoLeague, TeamLogoRegistryEntry> = ",
    ]
    lines.append(json.dumps(registry, indent=2) + " as const;\n")
    REGISTRY_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote registry {REGISTRY_PATH}")


def main() -> None:
    print(f"Downloading ESPN team logos to {OUT_ROOT}")
    registry: dict[str, dict] = {}
    for folder, (sport, league, query) in LEAGUES.items():
        print(f"League {folder} ({sport}/{league})...")
        registry[folder] = sync_league(folder, sport, league, query)
    emit_registry(registry)
    print("Done.")


if __name__ == "__main__":
    main()
