#!/usr/bin/env python3
"""
Sync team primary/secondary colors from ESPN into frontend team color registry.

Usage (from repo root):
  cd backend && PYTHONPATH=. python3 scripts/sync_team_colors.py
"""

from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
REGISTRY_PATH = (
    REPO_ROOT / "frontend" / "src" / "lib" / "team-colors-registry.generated.ts"
)

# YetAI folder key -> ESPN (sport, league, query)
LEAGUES: dict[str, tuple[str, str, str]] = {
    "mlb": ("baseball", "mlb", ""),
    "nfl": ("football", "nfl", ""),
    "nba": ("basketball", "nba", ""),
    "wnba": ("basketball", "wnba", ""),
    "nhl": ("hockey", "nhl", ""),
    "epl": ("soccer", "eng.1", ""),
    "mls": ("soccer", "usa.1", ""),
    "ucl": ("soccer", "uefa.champions", ""),
    "ncaaf": ("football", "college-football", "?limit=500"),
    "ncaab": ("basketball", "mens-college-basketball", "?limit=400"),
}

USER_AGENT = "YetAI-color-sync/1.0 (+https://github.com/benyetra/YetAI)"
DEFAULT_PRIMARY = "#444444"
DEFAULT_SECONDARY = "#888888"


def name_slug(display_name: str) -> str:
    s = display_name.strip().lower()
    s = s.replace("&", " and ")
    s = re.sub(r"[.'']", "", s)
    s = re.sub(r"[^a-z0-9]+", "_", s)
    return s.strip("_")


def fetch_json(url: str) -> dict:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.load(resp)


def normalize_hex(color: str | None, fallback: str) -> str:
    if not color:
        return fallback
    c = color.strip().lstrip("#")
    if not c:
        return fallback
    if len(c) == 3:
        c = "".join(ch * 2 for ch in c)
    if len(c) != 6 or not re.fullmatch(r"[0-9a-fA-F]{6}", c):
        return fallback
    return f"#{c.lower()}"


def load_teams(sport: str, league: str, query: str) -> list[dict]:
    url = (
        f"https://site.api.espn.com/apis/site/v2/sports/{sport}/{league}/teams"
        f"{query}"
    )
    data = fetch_json(url)
    return data["sports"][0]["leagues"][0]["teams"]


def sync_league(folder: str, sport: str, league: str, query: str) -> dict:
    teams = load_teams(sport, league, query)

    by_name: dict[str, dict[str, str]] = {}
    by_abbr: dict[str, dict[str, str]] = {}
    abbr_counts: dict[str, int] = {}

    for entry in teams:
        team = entry.get("team") or {}
        display = (team.get("displayName") or team.get("name") or "").strip()
        abbr = (team.get("abbreviation") or "").strip().upper()
        if not display:
            continue

        stem = name_slug(display)
        if not stem:
            continue

        colors = {
            "primary": normalize_hex(team.get("color"), DEFAULT_PRIMARY),
            "secondary": normalize_hex(team.get("alternateColor"), DEFAULT_SECONDARY),
        }
        by_name[stem] = colors

        if abbr:
            abbr_counts[abbr] = abbr_counts.get(abbr, 0) + 1

    for entry in teams:
        team = entry.get("team") or {}
        display = (team.get("displayName") or team.get("name") or "").strip()
        abbr = (team.get("abbreviation") or "").strip().upper()
        if not display or not abbr or abbr_counts.get(abbr, 0) != 1:
            continue
        stem = name_slug(display)
        if stem and stem in by_name:
            by_abbr[abbr] = by_name[stem]

    print(f"  {folder}: {len(by_name)} teams, {len(by_abbr)} abbr aliases")
    return {"byName": by_name, "byAbbr": by_abbr}


def emit_registry(registry: dict) -> None:
    lines = [
        "/** Auto-generated by backend/scripts/sync_team_colors.py — do not edit. */",
        "",
        "export type TeamColorLeague =",
        "  | 'mlb'",
        "  | 'nfl'",
        "  | 'nba'",
        "  | 'wnba'",
        "  | 'nhl'",
        "  | 'epl'",
        "  | 'mls'",
        "  | 'ucl'",
        "  | 'ncaaf'",
        "  | 'ncaab';",
        "",
        "export type TeamColorPair = {",
        "  primary: string;",
        "  secondary: string;",
        "};",
        "",
        "export type TeamColorRegistryEntry = {",
        "  byName: Record<string, TeamColorPair>;",
        "  byAbbr: Record<string, TeamColorPair>;",
        "};",
        "",
        "export const TEAM_COLOR_REGISTRY: Record<TeamColorLeague, TeamColorRegistryEntry> = ",
    ]
    lines.append(json.dumps(registry, indent=2) + " as const;\n")
    REGISTRY_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote registry {REGISTRY_PATH}")


def main() -> None:
    print("Syncing team colors from ESPN...")
    registry: dict[str, dict] = {}
    for folder, (sport, league, query) in LEAGUES.items():
        print(f"League {folder} ({sport}/{league})...")
        registry[folder] = sync_league(folder, sport, league, query)
    emit_registry(registry)
    print("Done.")


if __name__ == "__main__":
    main()
