"""Add parlay_legs to yetai_bets table

Revision ID: 5bf429bc3438
Revises: 8bf475b1b59f
Create Date: 2025-08-18 13:19:16.223306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf429bc3438'
down_revision: Union[str, Sequence[str], None] = '8bf475b1b59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yetai_bets', sa.Column('parlay_legs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yetai_bets', 'parlay_legs')
    # ### end Alembic commands ###
