"""Initial migration - create all tables

Revision ID: 8bf475b1b59f
Revises:
Create Date: 2025-08-18 13:01:16.332753

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8bf475b1b59f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("sport_key", sa.String(length=100), nullable=False),
        sa.Column("sport_title", sa.String(length=100), nullable=False),
        sa.Column("home_team", sa.String(length=255), nullable=False),
        sa.Column("away_team", sa.String(length=255), nullable=False),
        sa.Column("commence_time", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "LIVE",
                "FINAL",
                "POSTPONED",
                "CANCELLED",
                name="gamestatus",
            ),
            nullable=True,
        ),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column("last_update", sa.DateTime(), nullable=True),
        sa.Column("venue", sa.String(length=255), nullable=True),
        sa.Column("weather", sa.JSON(), nullable=True),
        sa.Column("odds_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_games_id"), "games", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column(
            "subscription_tier",
            sa.Enum("FREE", "PRO", "ELITE", name="subscriptiontier"),
            nullable=True,
        ),
        sa.Column("subscription_expires_at", sa.DateTime(), nullable=True),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("favorite_teams", sa.JSON(), nullable=True),
        sa.Column("preferred_sports", sa.JSON(), nullable=True),
        sa.Column("notification_settings", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("verification_token", sa.String(length=255), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), nullable=True),
        sa.Column("totp_secret", sa.String(length=255), nullable=True),
        sa.Column("backup_codes", sa.JSON(), nullable=True),
        sa.Column("totp_last_used", sa.DateTime(), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("avatar_thumbnail", sa.String(length=500), nullable=True),
        sa.Column("reset_token", sa.String(length=255), nullable=True),
        sa.Column("reset_token_expires", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "bet_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("bet_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("old_status", sa.String(length=50), nullable=True),
        sa.Column("new_status", sa.String(length=50), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("bet_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bet_history_id"), "bet_history", ["id"], unique=False)
    op.create_table(
        "bet_limits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("daily_limit", sa.Float(), nullable=True),
        sa.Column("weekly_limit", sa.Float(), nullable=True),
        sa.Column("single_bet_limit", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bet_limits_id"), "bet_limits", ["id"], unique=False)
    op.create_table(
        "live_bets",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.String(length=255), nullable=False),
        sa.Column(
            "bet_type",
            sa.Enum("MONEYLINE", "SPREAD", "TOTAL", "PARLAY", "PROP", name="bettype"),
            nullable=False,
        ),
        sa.Column("selection", sa.String(length=255), nullable=False),
        sa.Column("odds", sa.Float(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("potential_win", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "WON",
                "LOST",
                "CANCELLED",
                "LIVE",
                "CASHED_OUT",
                name="betstatus",
            ),
            nullable=True,
        ),
        sa.Column("placed_at", sa.DateTime(), nullable=True),
        sa.Column("settled_at", sa.DateTime(), nullable=True),
        sa.Column("result_amount", sa.Float(), nullable=True),
        sa.Column("game_time", sa.String(length=50), nullable=True),
        sa.Column("current_score", sa.String(length=50), nullable=True),
        sa.Column("cash_out_available", sa.Boolean(), nullable=True),
        sa.Column("cash_out_value", sa.Float(), nullable=True),
        sa.Column("cashed_out_at", sa.DateTime(), nullable=True),
        sa.Column("cash_out_amount", sa.Float(), nullable=True),
        sa.Column("home_team", sa.String(length=255), nullable=True),
        sa.Column("away_team", sa.String(length=255), nullable=True),
        sa.Column("sport", sa.String(length=100), nullable=True),
        sa.Column("commence_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_live_bets_id"), "live_bets", ["id"], unique=False)
    op.create_table(
        "parlay_bets",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("total_odds", sa.Float(), nullable=False),
        sa.Column("potential_win", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "WON",
                "LOST",
                "CANCELLED",
                "LIVE",
                "CASHED_OUT",
                name="betstatus",
            ),
            nullable=True,
        ),
        sa.Column("placed_at", sa.DateTime(), nullable=True),
        sa.Column("settled_at", sa.DateTime(), nullable=True),
        sa.Column("result_amount", sa.Float(), nullable=True),
        sa.Column("leg_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parlay_bets_id"), "parlay_bets", ["id"], unique=False)
    op.create_index(
        op.f("ix_parlay_bets_user_id"), "parlay_bets", ["user_id"], unique=False
    )
    op.create_table(
        "shared_bets",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("bet_id", sa.String(length=255), nullable=True),
        sa.Column("parlay_id", sa.String(length=255), nullable=True),
        sa.Column("bet_data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shared_bets_id"), "shared_bets", ["id"], unique=False)
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_activity", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_token"),
    )
    op.create_index(op.f("ix_user_sessions_id"), "user_sessions", ["id"], unique=False)
    op.create_table(
        "yetai_bets",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("game_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "bet_type",
            sa.Enum("MONEYLINE", "SPREAD", "TOTAL", "PARLAY", "PROP", name="bettype"),
            nullable=False,
        ),
        sa.Column("selection", sa.String(length=255), nullable=False),
        sa.Column("odds", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column(
            "tier_requirement",
            sa.Enum("FREE", "PRO", "ELITE", name="subscriptiontier"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("settled_at", sa.DateTime(), nullable=True),
        sa.Column("result", sa.String(length=50), nullable=True),
        sa.Column("model_version", sa.String(length=100), nullable=True),
        sa.Column("prediction_factors", sa.JSON(), nullable=True),
        sa.Column("historical_accuracy", sa.Float(), nullable=True),
        sa.Column("home_team", sa.String(length=255), nullable=True),
        sa.Column("away_team", sa.String(length=255), nullable=True),
        sa.Column("sport", sa.String(length=100), nullable=True),
        sa.Column("commence_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_yetai_bets_id"), "yetai_bets", ["id"], unique=False)
    op.create_table(
        "bets",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.String(length=255), nullable=True),
        sa.Column("parlay_id", sa.String(length=255), nullable=True),
        sa.Column(
            "bet_type",
            sa.Enum("MONEYLINE", "SPREAD", "TOTAL", "PARLAY", "PROP", name="bettype"),
            nullable=False,
        ),
        sa.Column("selection", sa.String(length=255), nullable=False),
        sa.Column("odds", sa.Float(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("potential_win", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "WON",
                "LOST",
                "CANCELLED",
                "LIVE",
                "CASHED_OUT",
                name="betstatus",
            ),
            nullable=True,
        ),
        sa.Column("placed_at", sa.DateTime(), nullable=True),
        sa.Column("settled_at", sa.DateTime(), nullable=True),
        sa.Column("result_amount", sa.Float(), nullable=True),
        sa.Column("home_team", sa.String(length=255), nullable=True),
        sa.Column("away_team", sa.String(length=255), nullable=True),
        sa.Column("sport", sa.String(length=100), nullable=True),
        sa.Column("commence_time", sa.DateTime(), nullable=True),
        sa.Column("bookmaker", sa.String(length=100), nullable=True),
        sa.Column("line_value", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parlay_id"],
            ["parlay_bets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bets_id"), "bets", ["id"], unique=False)
    op.create_index(op.f("ix_bets_user_id"), "bets", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bets_user_id"), table_name="bets")
    op.drop_index(op.f("ix_bets_id"), table_name="bets")
    op.drop_table("bets")
    op.drop_index(op.f("ix_yetai_bets_id"), table_name="yetai_bets")
    op.drop_table("yetai_bets")
    op.drop_index(op.f("ix_user_sessions_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_shared_bets_id"), table_name="shared_bets")
    op.drop_table("shared_bets")
    op.drop_index(op.f("ix_parlay_bets_user_id"), table_name="parlay_bets")
    op.drop_index(op.f("ix_parlay_bets_id"), table_name="parlay_bets")
    op.drop_table("parlay_bets")
    op.drop_index(op.f("ix_live_bets_id"), table_name="live_bets")
    op.drop_table("live_bets")
    op.drop_index(op.f("ix_bet_limits_id"), table_name="bet_limits")
    op.drop_table("bet_limits")
    op.drop_index(op.f("ix_bet_history_id"), table_name="bet_history")
    op.drop_table("bet_history")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_games_id"), table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###
