"""Remove foreign key constraint from live_bets.game_id

Revision ID: ed8098e2bdd1
Revises: 5bf429bc3438
Create Date: 2025-08-18 21:54:38.608847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8098e2bdd1'
down_revision: Union[str, Sequence[str], None] = '5bf429bc3438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('live_bets_game_id_fkey'), 'live_bets', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('live_bets_game_id_fkey'), 'live_bets', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###
